# Generated by Django 5.1.3 on 2024-11-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_questiontypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionTypes',
            new_name='QuestionType',
        ),
    ]
