# Generated by Django 5.1.3 on 2024-11-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_rename_questiontypes_questiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.questiontype')),
            ],
        ),
    ]
