# Generated by Django 5.1.3 on 2024-11-07 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.brand')),
                ('questions', models.ManyToManyField(to='surveys.question')),
            ],
        ),
    ]
