# Generated by Django 5.1.3 on 2024-11-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='questions',
            new_name='question_ids',
        ),
    ]
