# Generated by Django 5.1.3 on 2024-11-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_answerchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice_id', models.ManyToManyField(to='surveys.answerchoice')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.question')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.survey')),
            ],
        ),
    ]
