# Generated by Django 5.1.3 on 2024-11-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_location_occupation_participant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyQuestionAnswers',
            new_name='SurveyQuestionAnswerChoices',
        ),
    ]
