# Generated by Django 5.1.3 on 2024-11-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0011_rename_surveyquestionanswerchoices_surveyquestionanswerchoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_type',
            new_name='question_type_id',
        ),
    ]
