# Generated by Django 5.1.3 on 2024-11-08 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_rename_question_type_question_question_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionAnswerChoiceCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice_id', models.ManyToManyField(to='surveys.answerchoice')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.question')),
            ],
        ),
        migrations.DeleteModel(
            name='SurveyQuestionAnswerChoice',
        ),
    ]
