# Generated by Django 5.1.3 on 2024-11-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0013_surveyquestionanswerchoicecombo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question_ids',
        ),
    ]
