# Generated by Django 5.1.3 on 2024-11-08 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0015_rename_surveyquestionanswerchoicecombo_questionandanswerchoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='question_answer_choice_combos_ids',
        ),
    ]
