# Generated by Django 5.1.3 on 2024-11-08 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0017_delete_questionandanswerchoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestionAndAnswerChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choices', models.ManyToManyField(to='surveys.answerchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.survey')),
            ],
        ),
    ]
