# Generated by Django 5.1.3 on 2024-11-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0018_surveyquestionandanswerchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
