# Generated by Django 5.1.3 on 2024-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0019_alter_answerchoice_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyQuestionAndAnswerChoices',
            new_name='SurveyQuestionAndAnswerChoice',
        ),
    ]
