# Generated by Django 5.1.3 on 2024-11-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0021_rename_answer_choices_surveyquestionandanswerchoice_answer_choice_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choice_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.answerchoice')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.participant')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.question')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_date', models.DateField()),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.participant')),
                ('survey_answer_ids', models.ManyToManyField(to='surveys.surveyanswer')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='surveys.survey')),
            ],
        ),
    ]
