# Generated by Django 5.1.3 on 2024-11-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0023_rename_brand_survey_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyanswer',
            name='answer_choice_id',
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='answer_choice_ids',
            field=models.ManyToManyField(to='surveys.answerchoice'),
        ),
    ]
